# Generated by Django 5.2.12 on 2026-04-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_type', models.CharField(choices=[('network', 'Network (LAN/WiFi)'), ('usb', 'USB'), ('none', 'No Printer')], default='none', max_length=10)),
                ('host', models.CharField(blank=True, default='', max_length=100)),
                ('port', models.IntegerField(default=9100)),
                ('vendor_id', models.CharField(blank=True, default='0x04b8', max_length=20)),
                ('product_id', models.CharField(blank=True, default='0x0202', max_length=20)),
                ('auto_print', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printer Config',
            },
        ),
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(default='LOCO Abu Shadi', max_length=100)),
                ('name_he', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant Config',
            },
        ),
    ]
