# Generated by Django 5.2.12 on 2026-03-26 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_he', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_he', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_he', models.CharField(blank=True, max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein', models.PositiveIntegerField(blank=True, null=True)),
                ('carbs', models.PositiveIntegerField(blank=True, null=True)),
                ('fat', models.PositiveIntegerField(blank=True, null=True)),
                ('allergens', models.CharField(blank=True, max_length=255)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('sold_by_weight', models.BooleanField(default=False)),
                ('weight_unit', models.CharField(blank=True, choices=[('gram', 'גרם / غرام'), ('100g', '100 גרם'), ('kg', 'ק"ג / كيلو')], default='100g', max_length=10)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='السعر لكل وحدة (100g/kg) — اتركه فارغاً إذا كان السعر ثابت', max_digits=8, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
                ('toppings', models.ManyToManyField(blank=True, related_name='menu_items', to='menu.topping')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
