# Generated by Django 5.2.12 on 2026-03-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_he', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='🥗', max_length=10)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='topping',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topping',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toppings', to='menu.toppinggroup'),
        ),
    ]
